let mock = {
  drivers: [
    {
      id: 1,
      name: 'Lewis Hamilton',
      number: 44,
      country: 'United Kingdom',
      team: 'Mercedes',
      image: 'hamilton.jpg',
    },
    {
      id: 2,
      name: 'George Russell',
      number: 63,
      country: 'United Kingdom',
      team: 'Mercedes',
      image: 'russell.jpg',
    },
    {
      id: 3,
      name: 'Max Verstappen',
      number: 1,
      country: 'Netherlands',
      team: 'Red Bull Racing',
      image: 'verstappen.jpg',
    },
    {
      id: 4,
      name: 'Sergio Perez',
      number: 11,
      country: 'Mexico',
      team: 'Red Bull Racing',
      image: 'perez.jpg',
    },
    {
      id: 5,
      name: 'Charles Leclerc',
      number: 16,
      country: 'Monaco',
      team: 'Ferrari',
      image: 'leclerc.jpg',
    },
    {
      id: 6,
      name: 'Carlos Sainz',
      number: 55,
      country: 'Spain',
      team: 'Ferrari',
      image: 'sainz.jpg',
    },
    {
      id: 7,
      name: 'Lando Norris',
      number: 4,
      country: 'United Kingdom',
      team: 'Mclaren',
      image: 'norris.jpg',
    },
    {
      id: 8,
      name: 'Daniel Ricciardo',
      number: 3,
      country: 'Australia',
      team: 'Mclaren',
      image: 'ricciardo.jpg',
    },
    {
      id: 9,
      name: 'Esteban Ocon',
      number: 31,
      country: 'France',
      team: 'Alpine',
      image: 'ocon.jpg',
    },
    {
      id: 10,
      name: 'Fernando Alonso',
      number: 14,
      country: 'Spain',
      team: 'Alpine',
      image: 'alonso.jpg',
    },
    {
      id: 11,
      name: 'Pierre Gasly',
      number: 10,
      country: 'France',
      team: 'AlphaTauri',
      image: 'gasly.jpg',
    },
    {
      id: 12,
      name: 'Yuki Tsunoda',
      number: 22,
      country: 'Japan',
      team: 'AlphaTauri',
      image: 'tsunoda.jpg',
    },
    {
      id: 13,
      name: 'Lance Stroll',
      number: 18,
      country: 'Canada',
      team: 'Aston Martin',
      image: 'stroll.jpg',
    },
    {
      id: 14,
      name: 'Sebastian Vettel',
      number: 5,
      country: 'Germany',
      team: 'Aston Martin',
      image: 'vettel.jpg',
    },
    {
      id: 15,
      name: 'Alexander Albon',
      number: 23,
      country: 'Thailand',
      team: 'Williams',
      image: 'albon.jpg',
    },
    {
      id: 16,
      name: 'Nicholas Latifi',
      number: 6,
      country: 'Canada',
      team: 'Williams',
      image: 'latifi.jpg',
    },
    {
      id: 17,
      name: 'Valtteri Bottas',
      number: 77,
      country: 'Finland',
      team: 'Alfa Romeo',
      image: 'bottas.jpg',
    },
    {
      id: 18,
      name: 'Zhou Guanyu',
      number: 24,
      country: 'China',
      team: 'Alfa Romeo',
      image: 'guanyu.jpg',
    },
    {
      id: 19,
      name: 'Mick Schumacher',
      number: 47,
      country: 'Germany',
      team: 'Haas',
      image: 'schumacher.jpg',
    },
    {
      id: 20,
      name: 'Kevin Magnussen',
      number: 20,
      country: 'Denmark',
      team: 'Haas',
      image: 'magnussen.jpg',
    },
  ],
  // eslint-disable-next-line no-unused-vars
  teams: [
    {
      id: 1,
      name: 'Mercedes',
      licensed_in: 'Germany',
      based_in: 'United Kingdom',
      logo: 'mercedes.png',
      championships: 8,
      drivers: [1, 2],
    },
    {
      id: 2,
      name: 'Red Bull Racing',
      licensed_in: 'Austria',
      based_in: 'United Kingdom',
      logo: 'redbull.png',
      championships: 4,
      drivers: [3, 4],
    },
    {
      id: 3,
      name: 'Ferrari',
      licensed_in: 'Italy',
      based_in: 'Italy',
      logo: 'ferrari.png',
      championships: 16,
      drivers: [5, 6],
    },
    {
      id: 4,
      name: 'Mclaren',
      licensed_in: 'United Kingdom',
      based_in: 'United Kingdom',
      logo: 'mclaren.png',
      championships: 8,
      drivers: [7, 8],
    },
    {
      id: 5,
      name: 'Alpine',
      licensed_in: 'France',
      based_in: 'United Kingdom',
      logo: 'alpine.png',
      championships: 2,
      drivers: [9, 10],
    },
    {
      id: 6,
      name: 'AlphaTauri',
      licensed_in: 'Italy',
      based_in: 'Italy',
      logo: 'alphatauri.png',
      championships: 0,
      drivers: [11, 12],
    },
    {
      id: 7,
      name: 'Aston Martin',
      licensed_in: 'United Kingdom',
      based_in: 'United Kingdom',
      logo: 'aston.jpeg',
      championships: 0,
      drivers: [13, 14],
    },
    {
      id: 8,
      name: 'Williams',
      licensed_in: 'United Kingdom',
      based_in: 'United Kingdom',
      logo: 'williams.png',
      championships: 9,
      drivers: [15, 16],
    },
    {
      id: 9,
      name: 'Alpha Romeo',
      licensed_in: 'Switzerland',
      based_in: 'Switzerland',
      logo: 'alpharomeo.png',
      championships: 0,
      drivers: [17, 18],
    },
    {
      id: 10,
      name: 'Haas',
      licensed_in: 'United States',
      based_in: 'United Kingdom',
      logo: 'haas.png',
      championships: 0,
      drivers: [19, 20],
    },
  ],
};

export default mock;
